In [1]:
import pandas as pd
import numpy as np 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [2]:
data = load_iris()

In [3]:
dir(data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
df = pd.DataFrame(data.data, columns = data.feature_names)

In [6]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
df['target'] = data.target

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [13]:
X = df.drop('target', axis=1)

In [14]:
y = df.target

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [16]:
X_train.shape

(120, 4)

In [17]:
X_test.shape

(30, 4)

In [19]:
model = SVC()
model.fit(X_train, y_train)
model.score(X_test, y_test)

1.0

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(SVC(), X, y, cv=3)

array([0.96, 0.98, 0.94])

In [23]:
cross_val_score(SVC(C = 1.0, kernel = 'linear', gamma = 'scale'), X, y, cv=3)

array([1.  , 1.  , 0.98])

In [24]:
cross_val_score(SVC(C = 1.0, kernel = 'rbf',), X, y, cv=3)

array([0.96, 0.98, 0.94])

In [26]:
cross_val_score(SVC(C = 10.0, kernel = 'poly', degree = 2), X, y, cv=3)

array([0.98, 0.94, 0.98])

In [28]:
kval = ['rbf', 'linear']
cval = [1, 10, 20]

In [31]:
for i in kval:
    for j in cval:
        score = cross_val_score(SVC(C = j, kernel=i, gamma='scale'), X, y, cv = 3)
        print(i, "-", j, np.average(score))

rbf - 1 0.96
rbf - 10 0.9733333333333333
rbf - 20 0.98
linear - 1 0.9933333333333333
linear - 10 0.9733333333333333
linear - 20 0.9666666666666667


In [32]:
from sklearn.model_selection import GridSearchCV

In [36]:
clf = GridSearchCV(SVC(gamma='scale'), {'kernel' : ['rbf', 'linear'], 'C':[1, 10, 20]}, cv=3)

In [37]:
clf

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [40]:
clf.fit(X, y)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [41]:
clf.cv_results_

{'mean_fit_time': array([0.00495092, 0.00165709, 0.00218678, 0.00166758, 0.00174594,
        0.00102131]),
 'std_fit_time': array([2.68118621e-03, 4.58736691e-04, 2.64346181e-04, 4.72950607e-04,
        5.21498592e-04, 7.00556752e-05]),
 'mean_score_time': array([0.00118764, 0.00066574, 0.00099198, 0.00084956, 0.00156363,
        0.00029325]),
 'std_score_time': array([0.00058844, 0.00047075, 0.00024934, 0.00064462, 0.00038796,
        0.00041472]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [43]:
final = pd.DataFrame(clf.cv_results_)
final

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.004951      0.002681         0.001188        0.000588       1   
1       0.001657      0.000459         0.000666        0.000471       1   
2       0.002187      0.000264         0.000992        0.000249      10   
3       0.001668      0.000473         0.000850        0.000645      10   
4       0.001746      0.000521         0.001564        0.000388      20   
5       0.001021      0.000070         0.000293        0.000415      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}               0.96   
1       linear   {'C': 1, 'kernel': 'linear'}               1.00   
2          rbf     {'C': 10, 'kernel': 'rbf'}               0.98   
3       linear  {'C': 10, 'kernel': 'linear'}               1.00   
4          rbf     {'C': 20, 'kernel': 'rbf'}               0.98   
5       linear  {'C': 20, 'kernel': 'linear'}               1.00   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0               0.98               0.94         0.960000        0.016330   
1               1.00               0.98         0.993333        0.009428   
2               1.00               0.94         0.973333        0.024944   
3               0.94               0.98         0.973333        0.024944   
4               0.98               0.98         0.980000        0.000000   
5               0.94               0.96         0.966667        0.024944   

   rank_test_score  
0                6  
1                1  
2                3  
3                3  
4                2  
5                5

In [44]:
final[['params', 'mean_test_score','rank_test_score']]

params  mean_test_score  rank_test_score
0      {'C': 1, 'kernel': 'rbf'}         0.960000                6
1   {'C': 1, 'kernel': 'linear'}         0.993333                1
2     {'C': 10, 'kernel': 'rbf'}         0.973333                3
3  {'C': 10, 'kernel': 'linear'}         0.973333                3
4     {'C': 20, 'kernel': 'rbf'}         0.980000                2
5  {'C': 20, 'kernel': 'linear'}         0.966667                5

In [45]:
from sklearn.model_selection import RandomizedSearchCV

In [46]:
clf = RandomizedSearchCV(SVC(gamma='scale'), {'kernel' : ['rbf', 'linear', 'poly'], 'C':[1, 10, 20]}, cv=3, n_iter=3)

In [47]:
clf

RandomizedSearchCV(cv=3, estimator=SVC(), n_iter=3,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear', 'poly']})

In [48]:
clf.fit(X, y)

RandomizedSearchCV(cv=3, estimator=SVC(), n_iter=3,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear', 'poly']})

In [49]:
clf.cv_results_

{'mean_fit_time': array([0.00693289, 0.00321865, 0.00257754]),
 'std_fit_time': array([0.00408823, 0.00032345, 0.00040852]),
 'mean_score_time': array([0.00478697, 0.00198476, 0.0016195 ]),
 'std_score_time': array([1.56782277e-03, 3.10599620e-05, 4.06564214e-04]),
 'param_kernel': masked_array(data=['rbf', 'rbf', 'linear'],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[20, 10, 20],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rbf', 'C': 20},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'linear', 'C': 20}],
 'split0_test_score': array([0.98, 0.98, 1.  ]),
 'split1_test_score': array([0.98, 1.  , 0.94]),
 'split2_test_score': array([0.98, 0.94, 0.96]),
 'mean_test_score': array([0.98      , 0.97333333, 0.96666667]),
 'std_test_score': array([0.        , 0.02494438, 0.02494438]),
 'rank_test_score': array([1, 2, 3])}

In [50]:
final1 = pd.DataFrame(clf.cv_results_)

In [51]:
final1

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.006933      0.004088         0.004787        0.001568          rbf   
1       0.003219      0.000323         0.001985        0.000031          rbf   
2       0.002578      0.000409         0.001619        0.000407       linear   

  param_C                         params  split0_test_score  \
0      20     {'kernel': 'rbf', 'C': 20}               0.98   
1      10     {'kernel': 'rbf', 'C': 10}               0.98   
2      20  {'kernel': 'linear', 'C': 20}               1.00   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0               0.98               0.98         0.980000        0.000000   
1               1.00               0.94         0.973333        0.024944   
2               0.94               0.96         0.966667        0.024944   

   rank_test_score  
0                1  
1                2  
2                3