In [1]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()

In [3]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.33, random_state=42)

In [4]:
X_train.shape

(1203, 64)

In [5]:
X_test.shape

(594, 64)

In [6]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

D:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [7]:
sv = SVC()
sv.fit(X_train, y_train)
sv.score(X_test, y_test)

0.9865319865319865

In [8]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9781144781144782

In [9]:
def get_score(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [10]:
get_score(lr, X_train, y_train, X_test, y_test)

D:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [11]:
get_score(sv, X_train, y_train, X_test, y_test)

0.9865319865319865

In [12]:
get_score(rf, X_train, y_train, X_test, y_test)

0.9730639730639731

In [13]:
from sklearn.model_selection import KFold

In [14]:
fold = KFold()

In [15]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
fold = KFold(n_splits=3)

In [17]:
fold.split(l)

<generator object _BaseKFold.split at 0x0000027FF858EC20>

In [18]:
for train_index, test_index in fold.split(l):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [19]:
from sklearn.model_selection import StratifiedKFold

In [20]:
kf = StratifiedKFold(n_splits=3)

In [21]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
l1 = [0,0,0,1,1,1,2,2,2]
l1

[0, 0, 0, 1, 1, 1, 2, 2, 2]

In [23]:
for train_index, test_index in kf.split(l,l1):
    print(train_index, test_index)

[1 2 4 5 7 8] [0 3 6]
[0 2 3 5 6 8] [1 4 7]
[0 1 3 4 6 7] [2 5 8]


In [24]:
lr_score = []
svm_score = []
rf_score = []

In [25]:
for train_index, test_index in kf.split(digits.data, digits.target):
 #   print(train_index, test_index)
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]
    lr_score.append(get_score(lr, X_train, y_train, X_test, y_test))
    svm_score.append(get_score(sv, X_train, y_train, X_test, y_test))
    rf_score.append(get_score(rf, X_train, y_train, X_test, y_test))

D:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

In [26]:
lr_score

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [27]:
svm_score

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [28]:
rf_score

[0.9432387312186978, 0.9549248747913188, 0.9348914858096828]

In [29]:
np.mean(lr_score)

0.9265442404006677

In [30]:
np.mean(svm_score)

0.9699499165275459

In [31]:
np.mean(rf_score)

0.9443516972732331

In [32]:
from sklearn.model_selection import cross_val_score

In [33]:
cross_val_score(LogisticRegression(max_iter=7600), digits.data, digits.target, cv=5)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [34]:
cross_val_score(SVC(), digits.data, digits.target, cv=5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [35]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=5)

array([0.94444444, 0.90833333, 0.95821727, 0.95821727, 0.9275766 ])

In [36]:
cross_val_score(SVC(kernel = 'sigmoid'), digits.data, digits.target, cv = 3)

array([0.86978297, 0.90651085, 0.87646077])

In [37]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [39]:
cross_val_score(SVC(C=10), digits.data, digits.target, cv=3)

array([0.96828047, 0.97996661, 0.97328881])